services:
  backend:
    image: hako-backend-dev
    container_name: hako-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app/backend

    # External socket for testing purposes
    environment:
      - DOCKER_HOST=${DOCKER_TEST_SOCKET}
