# Clean image from Node
FROM node:22-bookworm

WORKDIR /app/backend

COPY . /app/backend/

# Install services
# -- Docker:
RUN chmod +x ./scripts/install-docker.sh
RUN ./scripts/install-docker.sh

# Install Node dependencies
RUN npm install

EXPOSE 3000

RUN chmod +x ./scripts/init.dev.sh
CMD ["/bin/sh", "-c", "./scripts/init.dev.sh"]
