services:
  backend:
    image: hako-backend-dev
    container_name: hako-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "${DOCKER_SOCKET}:/var/run/docker.sock"
      - .:/app/backend
